# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Custom Transition' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Custom Transition
  pod 'PureLayout', '~> 3.0.2'
  pod 'SVGKit'

  target 'Custom TransitionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Custom TransitionUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
